In [1]:
import pandas as pd
import openpyxl

In [16]:
# code that had be used for extracting the data

# Corona
# print("Corona Düsseldorf")
df = pd.read_csv("C:/Users/jkr/Documents/9 Computer/Informatik/Techlabs/DataScienceTrack/Project_DS/VSCode/techLabs/Datasets/Raw/Corona/duesseldorf_corona.csv")

display(df)
#print(df)

# Airquality Particulate Matter

print("Airquality Particulate Matter - 2020 - 2022")
df = pd.read_csv("C:/Users/jkr/Documents/9 Computer/Informatik/Techlabs/DataScienceTrack/Project_DS/VSCode/techLabs/Datasets/Raw/AirQuality/Particulate Matter/2020-2022 Feinstaub NRW Stundenmittelwert.csv", encoding="ISO-8859-1", sep=";")

print(df.dtypes)

display(df)
#print(df)

,IdLandkreis,Altersgruppe,Geschlecht,Meldedatum,Refdatum,IstErkrankungsbeginn,NeuerFall,NeuerTodesfall,NeuGenesen,AnzahlFall,AnzahlTodesfall,AnzahlGenesen
0,5111,A35-A59,M,2020-04-03,2020-02-18,1,0,-9,0,1,0,1
1,5111,A35-A59,M,2020-03-04,2020-02-24,1,0,-9,0,1,0,1
2,5111,A60-A79,M,2020-03-13,2020-02-25,1,0,-9,0,1,0,1
3,5111,A35-A59,M,2020-04-21,2020-02-25,1,0,-9,0,1,0,1
4,5111,A35-A59,M,2020-03-09,2020-02-28,1,0,-9,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
31828,5111,A60-A79,W,2024-01-15,2024-01-15,0,0,-9,-9,3,0,0
31829,5111,A15-A34,W,2024-01-15,2024-01-15,0,0,-9,-9,1,0,0
31830,5111,A00-A04,W,2024-01-15,2024-01-15,0,0,-9,-9,1,0,0
31831,5111,A35-A59,W,2024-01-15,2024-01-15,0,0,-9,-9,2,0,0
31832,5111,A80+,W,2024-01-16,2024-01-16,0,1,-9,-9,1,0,0

Airquality Particulate Matter - 2020 - 2022
# "Tabelle für Zeitbereich: 01.01.2020 00:00 bis 01.01.2023 00:00"    object
Unnamed: 1                                                            object
Unnamed: 2                                                            object
Unnamed: 3                                                            object
Unnamed: 4                                                            object
                                                                       ...
Unnamed: 58                                                           object
Unnamed: 59                                                           object
Unnamed: 60                                                           object
Unnamed: 61                                                           object
Unnamed: 62                                                           object
Length: 63, dtype: object

C:\Users\jkr\AppData\Local\Temp\ipykernel_10800\2508748753.py:13: DtypeWarning: Columns (14,38,41,46,60) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("C:/Users/jkr/Documents/9 Computer/Informatik/Techlabs/DataScienceTrack/Project_DS/VSCode/techLabs/Datasets/Raw/AirQuality/Particulate Matter/2020-2022 Feinstaub NRW Stundenmittelwert.csv", encoding="ISO-8859-1", sep=";")

,"# ""Tabelle für Zeitbereich: 01.01.2020 00:00 bis 01.01.2023 00:00""",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62
0,"# ""Quelle""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Datum,Zeit,AABU PM10F 24H gleitender Mittelwert [µg/m³],BIEL PM10F 24H gleitender Mittelwert [µg/m³],BONN PM10F 24H gleitender Mittelwert [µg/m³],BORG PM10F 24H gleitender Mittelwert [µg/m³],BOTT PM10F 24H gleitender Mittelwert [µg/m³],BUCH PM10F 24H gleitender Mittelwert [µg/m³],CHOR PM10F 24H gleitender Mittelwert [µg/m³],DATT PM10F 24H gleitender Mittelwert [µg/m³],...,VMS2 PM10F 24H gleitender Mittelwert [µg/m³],VOBD PM10F 24H gleitender Mittelwert [µg/m³],VOBM PM10F 24H gleitender Mittelwert [µg/m³],VSGK PM10F 24H gleitender Mittelwert [µg/m³],VWEL PM10F 24H gleitender Mittelwert [µg/m³],WALS PM10F 24H gleitender Mittelwert [µg/m³],WAST PM10F 24H gleitender Mittelwert [µg/m³],WESE PM10F 24H gleitender Mittelwert [µg/m³],WES2 PM10F 24H gleitender Mittelwert [µg/m³],WULA PM10F 24H gleitender Mittelwert [µg/m³]
2,01.01.2020,01:00,36,38,39,29,32,27,42,46,...,56,NaN,81,62,40,43,36,28,NaN,27
3,01.01.2020,02:00,45,43,53,30,33,28,51,47,...,61,NaN,119,65,45,44,37,33,NaN,35
4,01.01.2020,03:00,54,46,56,29,33,38,53,68,...,61,NaN,148,67,48,46,38,35,NaN,37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26301,31.12.2022,20:00,<10,<10,<10,<10,<10,<10,<10,<10,...,<10,<10,<10,<10,10,17,<10,NaN,<10,<10
26302,31.12.2022,21:00,<10,<10,<10,<10,10,<10,<10,<10,...,<10,<10,<10,<10,11,19,<10,NaN,<10,<10
26303,31.12.2022,22:00,<10,<10,<10,<10,12,<10,<10,<10,...,<10,<10,<10,<10,11,21,<10,NaN,<10,<10
26304,31.12.2022,23:00,<10,<10,<10,<10,13,<10,10,<10,...,<10,<10,<10,<10,12,22,<10,NaN,<10,<10
26305,31.12.2022,24:00:00,<10,<10,<10,<10,14,<10,11,<10,...,<10,<10,<10,<10,13,23,<10,NaN,<10,<10

In [14]:
# in Spalten 14, 38, 41, 46, 60 sind wohl gemischte types vorhanden, mal sehen was da drin steht

selected_columns = df.iloc[:, [14, 38, 41, 46, 60]]
print(selected_columns.dtypes)
display(selected_columns)

Unnamed: 14    object
Unnamed: 38    object
Unnamed: 41    object
Unnamed: 46    object
Unnamed: 60    object
dtype: object

,Unnamed: 14,Unnamed: 38,Unnamed: 41,Unnamed: 46,Unnamed: 60
0,NaN,NaN,NaN,NaN,NaN
1,DWER PM10F 24H gleitender Mittelwert [µg/m³],VBIH PM10F 24H gleitender Mittelwert [µg/m³],VDOR PM10F 24H gleitender Mittelwert [µg/m³],VGLG PM10F 24H gleitender Mittelwert [µg/m³],WESE PM10F 24H gleitender Mittelwert [µg/m³]
2,31,47,37,76,28
3,31,53,52,108,33
4,36,57,57,126,35
...,...,...,...,...,...
26301,NaN,NaN,NaN,NaN,NaN
26302,NaN,NaN,NaN,NaN,NaN
26303,NaN,NaN,NaN,NaN,NaN
26304,NaN,NaN,NaN,NaN,NaN
26305,NaN,NaN,NaN,NaN,NaN